name: Label Pull Requests

on:
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

jobs:
  label_pull_requests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Label Pull Requests
      uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
